using System.Diagnostics.CodeAnalysis;

using Windows.Win32.Graphics.DirectWrite;

namespace Stylish.DirectWrite.Formatting;

/// <inheritdoc cref="DWRITE_FONT_WEIGHT" />
[ SuppressMessage ( "Design", "CA1069:Enums values should not be duplicated", Justification = "DWRITE_FONT_WEIGHT" ) ]
[ SuppressMessage ( "Design", "CA1008:Enums should have zero value",          Justification = "DWRITE_FONT_WEIGHT" ) ]
public enum FontWeight
{
    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_THIN" />
    Thin = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_THIN,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_LIGHT" />
    ExtraLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_LIGHT,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_LIGHT" />
    UltraLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_LIGHT,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_LIGHT" />
    Light = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_LIGHT,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_LIGHT" />
    SemiLight = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_LIGHT,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_NORMAL" />
    Normal = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_NORMAL,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_REGULAR" />
    Regular = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_REGULAR,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_MEDIUM" />
    Medium = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_MEDIUM,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_DEMI_BOLD" />
    DemiBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_DEMI_BOLD,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_BOLD" />
    SemiBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_SEMI_BOLD,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_BOLD" />
    Bold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_BOLD,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BOLD" />
    ExtraBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BOLD,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BOLD" />
    UltraBold = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BOLD,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_BLACK" />
    Black = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_BLACK,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_HEAVY" />
    Heavy = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_HEAVY,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BLACK" />
    ExtraBlack = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_EXTRA_BLACK,

    /// <inheritdoc cref="DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BLACK" />
    UltraBlack = DWRITE_FONT_WEIGHT.DWRITE_FONT_WEIGHT_ULTRA_BLACK
}