using Windows.Win32.Graphics.DirectWrite;

namespace Stylish.DirectWrite.Formatting;

/// <inheritdoc cref="DWRITE_READING_DIRECTION" />
public enum ReadingDirection
{
    /// <inheritdoc cref="DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_LEFT_TO_RIGHT" />
    LeftToRight = DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_LEFT_TO_RIGHT,

    /// <inheritdoc cref="DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_RIGHT_TO_LEFT" />
    RightToLeft = DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_RIGHT_TO_LEFT,

    /// <inheritdoc cref="DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_TOP_TO_BOTTOM" />
    TopToBottom = DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_TOP_TO_BOTTOM,

    /// <inheritdoc cref="DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_BOTTOM_TO_TOP" />
    BottomToTop = DWRITE_READING_DIRECTION.DWRITE_READING_DIRECTION_BOTTOM_TO_TOP
}