using Windows.Win32.Graphics.DirectWrite;

namespace Stylish.DirectWrite.Formatting;

/// <inheritdoc cref="DWRITE_WORD_WRAPPING" />
public enum WordWrapping
{
    /// <inheritdoc cref="DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WRAP" />
    Wrap = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WRAP,

    /// <inheritdoc cref="DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_NO_WRAP" />
    NoWrap = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_NO_WRAP,

    /// <inheritdoc cref="DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_EMERGENCY_BREAK" />
    EmergencyBreak = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_EMERGENCY_BREAK,

    /// <inheritdoc cref="DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WHOLE_WORD" />
    WholeWord = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_WHOLE_WORD,

    /// <inheritdoc cref="DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_CHARACTER" />
    Character = DWRITE_WORD_WRAPPING.DWRITE_WORD_WRAPPING_CHARACTER
}