using System.Runtime.CompilerServices;
using System.Text;

using Stylish.Unicode;

namespace Stylish.Fonts;

public static class SegoeConverter
{
    public static string ToUnicode ( this Emoji emoji, Variant variant = Variant.None )
    {
        return EmojiEncoding.Decode ( (long) emoji, variant );
    }

    public static string ToUnicode ( this SegoeFluentIcons fluent ) => Decode ( (int) fluent );
    public static string ToUnicode ( this SegoeMDL2Assets  mdl2   ) => Decode ( (int) mdl2   );
    public static string ToUnicode ( this SegoeUISymbol    symbol ) => Decode ( (int) symbol );

    [ MethodImpl ( MethodImplOptions.AggressiveInlining ) ]
    private static string Decode ( int codepoint ) => new Rune ( codepoint ).ToString ( );

    public static SegoeFluentIcons ToFluent ( this SegoeMDL2Assets mdl2 ) => mdl2 switch
    {
        SegoeMDL2Assets.DoublePortrait  or
        SegoeMDL2Assets.DoubleLandscape or
        SegoeMDL2Assets.SinglePortrait  or
        SegoeMDL2Assets.SingleLandscape => SegoeFluentIcons.None,
        _                               => (SegoeFluentIcons) mdl2
    };

    public static SegoeFluentIcons ToFluent ( this SegoeUISymbol symbol )
    {
        return (SegoeFluentIcons) ToMDL2 ( symbol );
    }

    public static SegoeMDL2Assets ToMDL2 ( this SegoeFluentIcons fluent ) => fluent switch
    {
        SegoeFluentIcons.Move                        or
        SegoeFluentIcons.GatewayRouter               or
        SegoeFluentIcons.CloudDownload               or
        SegoeFluentIcons.HoloLens                    or
        SegoeFluentIcons.POI                         or
        SegoeFluentIcons.Hide                        or
        SegoeFluentIcons.CaretLeft8                  or
        SegoeFluentIcons.CaretUp8                    or
        SegoeFluentIcons.CaretDown8                  or
        SegoeFluentIcons.MarketDown                  or
        SegoeFluentIcons.ZipFolder                   or
        SegoeFluentIcons.CaretSolidLeft              or
        SegoeFluentIcons.CaretSolidDown              or
        SegoeFluentIcons.CaretSolidRight             or
        SegoeFluentIcons.CaretSolidUp                or
        SegoeFluentIcons.ClosedCaptionsInternational or
        SegoeFluentIcons.DocumentApproval            or
        SegoeFluentIcons.DeclineCall                 or
        SegoeFluentIcons.IDBadge                     or
        SegoeFluentIcons.MicLocationCombo            or
        SegoeFluentIcons.Event12                     => SegoeMDL2Assets.None,
        _                                            => (SegoeMDL2Assets) fluent
    };

    public static SegoeMDL2Assets ToMDL2 ( this SegoeUISymbol symbol ) => symbol switch
    {
        SegoeUISymbol.None              => SegoeMDL2Assets.None,
        SegoeUISymbol.MapPin            => SegoeMDL2Assets.MapPin,
        SegoeUISymbol.Edit              => SegoeMDL2Assets.Edit,
        SegoeUISymbol.Add               => SegoeMDL2Assets.Add,
        SegoeUISymbol.More              => SegoeMDL2Assets.More,
        SegoeUISymbol.Settings          => SegoeMDL2Assets.Settings,
        SegoeUISymbol.Video             => SegoeMDL2Assets.Video,
        SegoeUISymbol.Mail              => SegoeMDL2Assets.Mail,
        SegoeUISymbol.People            => SegoeMDL2Assets.People,
        SegoeUISymbol.Phone             => SegoeMDL2Assets.Phone,
        SegoeUISymbol.Pin               => SegoeMDL2Assets.Pin,
        SegoeUISymbol.Shop              => SegoeMDL2Assets.Shop,
        SegoeUISymbol.Stop              => SegoeMDL2Assets.Stop,
        SegoeUISymbol.Link              => SegoeMDL2Assets.Link,
        SegoeUISymbol.Filter            => SegoeMDL2Assets.Filter,
        SegoeUISymbol.AllApps           => SegoeMDL2Assets.AllApps,
        SegoeUISymbol.Zoom              => SegoeMDL2Assets.Zoom,
        SegoeUISymbol.ZoomOut           => SegoeMDL2Assets.ZoomOut,
        SegoeUISymbol.Microphone        => SegoeMDL2Assets.Microphone,
        SegoeUISymbol.Search            => SegoeMDL2Assets.Search,
        SegoeUISymbol.Attach            => SegoeMDL2Assets.Attach,
        SegoeUISymbol.Send              => SegoeMDL2Assets.Send,
        SegoeUISymbol.Refresh           => SegoeMDL2Assets.Refresh,
        SegoeUISymbol.ReportHacked      => SegoeMDL2Assets.ReportHacked,
        SegoeUISymbol.Remove            => SegoeMDL2Assets.Remove,
        SegoeUISymbol.BackToWindow      => SegoeMDL2Assets.BackToWindow,
        SegoeUISymbol.FullScreen        => SegoeMDL2Assets.FullScreen,
        SegoeUISymbol.Delete            => SegoeMDL2Assets.Delete,
        SegoeUISymbol.Save              => SegoeMDL2Assets.Save,
        SegoeUISymbol.Mute              => SegoeMDL2Assets.Mute,
        SegoeUISymbol.Volume            => SegoeMDL2Assets.Volume,
        SegoeUISymbol.Emoji2            => SegoeMDL2Assets.Emoji2,
        SegoeUISymbol.Globe             => SegoeMDL2Assets.Globe,
        SegoeUISymbol.HangUp            => SegoeMDL2Assets.HangUp,
        SegoeUISymbol.ContactInfo       => SegoeMDL2Assets.ContactInfo,
        SegoeUISymbol.Unpin             => SegoeMDL2Assets.Unpin,
        SegoeUISymbol.Contact           => SegoeMDL2Assets.Contact,
        SegoeUISymbol.Memo              => SegoeMDL2Assets.Memo,
        SegoeUISymbol.Paste             => SegoeMDL2Assets.Paste,
        SegoeUISymbol.PhoneBook         => SegoeMDL2Assets.PhoneBook,
        SegoeUISymbol.Slideshow         => SegoeMDL2Assets.Slideshow,
        SegoeUISymbol.Calendar          => SegoeMDL2Assets.Calendar,
        SegoeUISymbol.Trim              => SegoeMDL2Assets.Trim,
        SegoeUISymbol.NewWindow         => SegoeMDL2Assets.NewWindow,
        SegoeUISymbol.SaveLocal         => SegoeMDL2Assets.SaveLocal,
        SegoeUISymbol.Redo              => SegoeMDL2Assets.Redo,
        SegoeUISymbol.Undo              => SegoeMDL2Assets.Undo,
        SegoeUISymbol.Crop              => SegoeMDL2Assets.Crop,
        SegoeUISymbol.OpenWith          => SegoeMDL2Assets.OpenWith,
        SegoeUISymbol.Rotate            => SegoeMDL2Assets.Rotate,
        SegoeUISymbol.SetLockScreen     => SegoeMDL2Assets.SetLockScreen,
        SegoeUISymbol.Flag              => SegoeMDL2Assets.Flag,
        SegoeUISymbol.Page              => SegoeMDL2Assets.Page,
        SegoeUISymbol.BrowsePhotos      => SegoeMDL2Assets.BrowsePhotos,
        SegoeUISymbol.TouchPointer      => SegoeMDL2Assets.TouchPointer,
        SegoeUISymbol.Highlight         => SegoeMDL2Assets.Highlight,
        SegoeUISymbol.OtherUser         => SegoeMDL2Assets.OtherUser,
        SegoeUISymbol.Admin             => SegoeMDL2Assets.Admin,
        SegoeUISymbol.CC                => SegoeMDL2Assets.CC,
        SegoeUISymbol.Home              => SegoeMDL2Assets.Home,
        SegoeUISymbol.View              => SegoeMDL2Assets.View,
        SegoeUISymbol.Previous          => SegoeMDL2Assets.Previous,
        SegoeUISymbol.Next              => SegoeMDL2Assets.Next,
        SegoeUISymbol.Sync              => SegoeMDL2Assets.Sync,
        SegoeUISymbol.Download          => SegoeMDL2Assets.Download,
        SegoeUISymbol.Help              => SegoeMDL2Assets.Help,
        SegoeUISymbol.Upload            => SegoeMDL2Assets.Upload,
        SegoeUISymbol.Emoji             => SegoeMDL2Assets.Emoji,
        SegoeUISymbol.TwoPage           => SegoeMDL2Assets.TwoPage,
        SegoeUISymbol.LeaveChat         => SegoeMDL2Assets.LeaveChat,
        SegoeUISymbol.MailForward       => SegoeMDL2Assets.MailForward,
        SegoeUISymbol.RotateCamera      => SegoeMDL2Assets.RotateCamera,
        SegoeUISymbol.ClosePane         => SegoeMDL2Assets.ClosePane,
        SegoeUISymbol.OpenPane          => SegoeMDL2Assets.OpenPane,
        SegoeUISymbol.PreviewLink       => SegoeMDL2Assets.PreviewLink,
        SegoeUISymbol.AttachCamera      => SegoeMDL2Assets.AttachCamera,
        SegoeUISymbol.ZoomIn            => SegoeMDL2Assets.ZoomIn,
        SegoeUISymbol.Bookmarks         => SegoeMDL2Assets.Bookmarks,
        SegoeUISymbol.Document          => SegoeMDL2Assets.Document,
        SegoeUISymbol.ProtectedDocument => SegoeMDL2Assets.ProtectedDocument,
        SegoeUISymbol.ViewAll           => SegoeMDL2Assets.ViewAll,
        SegoeUISymbol.VideoChat         => SegoeMDL2Assets.VideoChat,
        SegoeUISymbol.Switch            => SegoeMDL2Assets.Switch,
        SegoeUISymbol.Rename            => SegoeMDL2Assets.Rename,
        SegoeUISymbol.Go                => SegoeMDL2Assets.Go,
        SegoeUISymbol.Remote            => SegoeMDL2Assets.Remote,
        SegoeUISymbol.Shuffle           => SegoeMDL2Assets.Shuffle,
        SegoeUISymbol.SelectAll         => SegoeMDL2Assets.SelectAll,
        SegoeUISymbol.Orientation       => SegoeMDL2Assets.Orientation,
        SegoeUISymbol.Import            => SegoeMDL2Assets.Import,
        SegoeUISymbol.ImportAll         => SegoeMDL2Assets.ImportAll,
        SegoeUISymbol.Folder            => SegoeMDL2Assets.Folder,
        SegoeUISymbol.Webcam            => SegoeMDL2Assets.Webcam,
        SegoeUISymbol.Caption           => SegoeMDL2Assets.Caption,
        SegoeUISymbol.ShowResults       => SegoeMDL2Assets.ShowResults,
        SegoeUISymbol.Message           => SegoeMDL2Assets.Message,
        SegoeUISymbol.CalendarDay       => SegoeMDL2Assets.CalendarDay,
        SegoeUISymbol.CalendarWeek      => SegoeMDL2Assets.CalendarWeek,
        SegoeUISymbol.Characters        => SegoeMDL2Assets.Characters,
        SegoeUISymbol.MailReplyAll      => SegoeMDL2Assets.MailReplyAll,
        SegoeUISymbol.Read              => SegoeMDL2Assets.Read,
        SegoeUISymbol.ShowBcc           => SegoeMDL2Assets.ShowBcc,
        SegoeUISymbol.HideBcc           => SegoeMDL2Assets.HideBcc,
        SegoeUISymbol.Cut               => SegoeMDL2Assets.Cut,
        SegoeUISymbol.Copy              => SegoeMDL2Assets.Copy,
        SegoeUISymbol.Important         => SegoeMDL2Assets.Important,
        SegoeUISymbol.MailReply         => SegoeMDL2Assets.MailReply,
        SegoeUISymbol.Sort              => SegoeMDL2Assets.Sort,
        SegoeUISymbol.DisconnectDrive   => SegoeMDL2Assets.DisconnectDrive,
        SegoeUISymbol.MapDrive          => SegoeMDL2Assets.MapDrive,
        SegoeUISymbol.ContactPresence   => SegoeMDL2Assets.ContactPresence,
        SegoeUISymbol.Priority          => SegoeMDL2Assets.Priority,
        SegoeUISymbol.GoToToday         => SegoeMDL2Assets.GoToToday,
        SegoeUISymbol.Font              => SegoeMDL2Assets.Font,
        SegoeUISymbol.FontColor         => SegoeMDL2Assets.FontColor,
        SegoeUISymbol.Contact2          => SegoeMDL2Assets.Contact2,
        SegoeUISymbol.Audio             => SegoeMDL2Assets.Audio,
        SegoeUISymbol.Permissions       => SegoeMDL2Assets.Permissions,
        SegoeUISymbol.DisableUpdates    => SegoeMDL2Assets.DisableUpdates,
        SegoeUISymbol.Unfavorite        => SegoeMDL2Assets.Unfavorite,
        SegoeUISymbol.OpenLocal         => SegoeMDL2Assets.OpenLocal,
        SegoeUISymbol.Italic            => SegoeMDL2Assets.Italic,
        SegoeUISymbol.Underline         => SegoeMDL2Assets.Underline,
        SegoeUISymbol.Bold              => SegoeMDL2Assets.Bold,
        SegoeUISymbol.MoveToFolder      => SegoeMDL2Assets.MoveToFolder,
        SegoeUISymbol.LikeDislike       => SegoeMDL2Assets.LikeDislike,
        SegoeUISymbol.Dislike           => SegoeMDL2Assets.Dislike,
        SegoeUISymbol.Like              => SegoeMDL2Assets.Like,
        SegoeUISymbol.AlignRight        => SegoeMDL2Assets.AlignRight,
        SegoeUISymbol.AlignCenter       => SegoeMDL2Assets.AlignCenter,
        SegoeUISymbol.AlignLeft         => SegoeMDL2Assets.AlignLeft,
        SegoeUISymbol.OpenFile          => SegoeMDL2Assets.OpenFile,
        SegoeUISymbol.ClearSelection    => SegoeMDL2Assets.ClearSelection,
        SegoeUISymbol.FontDecrease      => SegoeMDL2Assets.FontDecrease,
        SegoeUISymbol.FontIncrease      => SegoeMDL2Assets.FontIncrease,
        SegoeUISymbol.FontSize          => SegoeMDL2Assets.FontSize,
        SegoeUISymbol.CellPhone         => SegoeMDL2Assets.CellPhone,
        SegoeUISymbol.Reshare           => SegoeMDL2Assets.Reshare,
        SegoeUISymbol.Tag               => SegoeMDL2Assets.Tag,
        SegoeUISymbol.RepeatOne         => SegoeMDL2Assets.RepeatOne,
        SegoeUISymbol.RepeatAll         => SegoeMDL2Assets.RepeatAll,
        SegoeUISymbol.Calculator        => SegoeMDL2Assets.Calculator,
        SegoeUISymbol.Directions        => SegoeMDL2Assets.Directions,
        SegoeUISymbol.Library           => SegoeMDL2Assets.Library,
        SegoeUISymbol.PostUpdate        => SegoeMDL2Assets.PostUpdate,
        SegoeUISymbol.NewFolder         => SegoeMDL2Assets.NewFolder,
        SegoeUISymbol.CalendarReply     => SegoeMDL2Assets.CalendarReply,
        SegoeUISymbol.UnsyncFolder      => SegoeMDL2Assets.UnsyncFolder,
        SegoeUISymbol.SyncFolder        => SegoeMDL2Assets.SyncFolder,
        SegoeUISymbol.BlockContact      => SegoeMDL2Assets.BlockContact,
        SegoeUISymbol.SwitchApps        => SegoeMDL2Assets.SwitchApps,
        SegoeUISymbol.AddFriend         => SegoeMDL2Assets.AddFriend,
        SegoeUISymbol.GoToStart         => SegoeMDL2Assets.GoToStart,
        SegoeUISymbol.ZeroBars          => SegoeMDL2Assets.ZeroBars,
        SegoeUISymbol.OneBar            => SegoeMDL2Assets.OneBar,
        SegoeUISymbol.TwoBars           => SegoeMDL2Assets.TwoBars,
        SegoeUISymbol.ThreeBars         => SegoeMDL2Assets.ThreeBars,
        SegoeUISymbol.FourBars          => SegoeMDL2Assets.FourBars,
        SegoeUISymbol.World             => SegoeMDL2Assets.World,
        SegoeUISymbol.Comment           => SegoeMDL2Assets.Comment,
        SegoeUISymbol.MusicInfo         => SegoeMDL2Assets.MusicInfo,
        SegoeUISymbol.DockLeft          => SegoeMDL2Assets.DockLeft,
        SegoeUISymbol.DockRight         => SegoeMDL2Assets.DockRight,
        SegoeUISymbol.DockBottom        => SegoeMDL2Assets.DockBottom,
        SegoeUISymbol.Repair            => SegoeMDL2Assets.Repair,
        SegoeUISymbol.Accounts          => SegoeMDL2Assets.Accounts,
        SegoeUISymbol.Manage            => SegoeMDL2Assets.Manage,
        SegoeUISymbol.Street            => SegoeMDL2Assets.Street,
        SegoeUISymbol.Photo             => SegoeMDL2Assets.Photo,
        SegoeUISymbol.List              => SegoeMDL2Assets.List,
        _                               => SegoeMDL2Assets.None
    };

    public static SegoeUISymbol ToSymbol ( this SegoeFluentIcons fluent )
    {
        return ToSymbol ( (SegoeMDL2Assets) fluent );
    }

    public static SegoeUISymbol ToSymbol ( this SegoeMDL2Assets mdl2 ) => mdl2 switch
    {
        SegoeMDL2Assets.None              => SegoeUISymbol.None,
        SegoeMDL2Assets.MapPin            => SegoeUISymbol.MapPin,
        SegoeMDL2Assets.Edit              => SegoeUISymbol.Edit,
        SegoeMDL2Assets.Add               => SegoeUISymbol.Add,
        SegoeMDL2Assets.More              => SegoeUISymbol.More,
        SegoeMDL2Assets.Settings          => SegoeUISymbol.Settings,
        SegoeMDL2Assets.Video             => SegoeUISymbol.Video,
        SegoeMDL2Assets.Mail              => SegoeUISymbol.Mail,
        SegoeMDL2Assets.People            => SegoeUISymbol.People,
        SegoeMDL2Assets.Phone             => SegoeUISymbol.Phone,
        SegoeMDL2Assets.Pin               => SegoeUISymbol.Pin,
        SegoeMDL2Assets.Shop              => SegoeUISymbol.Shop,
        SegoeMDL2Assets.Stop              => SegoeUISymbol.Stop,
        SegoeMDL2Assets.Link              => SegoeUISymbol.Link,
        SegoeMDL2Assets.Filter            => SegoeUISymbol.Filter,
        SegoeMDL2Assets.AllApps           => SegoeUISymbol.AllApps,
        SegoeMDL2Assets.Zoom              => SegoeUISymbol.Zoom,
        SegoeMDL2Assets.ZoomOut           => SegoeUISymbol.ZoomOut,
        SegoeMDL2Assets.Microphone        => SegoeUISymbol.Microphone,
        SegoeMDL2Assets.Search            => SegoeUISymbol.Search,
        SegoeMDL2Assets.Attach            => SegoeUISymbol.Attach,
        SegoeMDL2Assets.Send              => SegoeUISymbol.Send,
        SegoeMDL2Assets.Refresh           => SegoeUISymbol.Refresh,
        SegoeMDL2Assets.ReportHacked      => SegoeUISymbol.ReportHacked,
        SegoeMDL2Assets.Remove            => SegoeUISymbol.Remove,
        SegoeMDL2Assets.BackToWindow      => SegoeUISymbol.BackToWindow,
        SegoeMDL2Assets.FullScreen        => SegoeUISymbol.FullScreen,
        SegoeMDL2Assets.Delete            => SegoeUISymbol.Delete,
        SegoeMDL2Assets.Save              => SegoeUISymbol.Save,
        SegoeMDL2Assets.Mute              => SegoeUISymbol.Mute,
        SegoeMDL2Assets.Volume            => SegoeUISymbol.Volume,
        SegoeMDL2Assets.Emoji2            => SegoeUISymbol.Emoji2,
        SegoeMDL2Assets.Globe             => SegoeUISymbol.Globe,
        SegoeMDL2Assets.HangUp            => SegoeUISymbol.HangUp,
        SegoeMDL2Assets.ContactInfo       => SegoeUISymbol.ContactInfo,
        SegoeMDL2Assets.Unpin             => SegoeUISymbol.Unpin,
        SegoeMDL2Assets.Contact           => SegoeUISymbol.Contact,
        SegoeMDL2Assets.Memo              => SegoeUISymbol.Memo,
        SegoeMDL2Assets.Paste             => SegoeUISymbol.Paste,
        SegoeMDL2Assets.PhoneBook         => SegoeUISymbol.PhoneBook,
        SegoeMDL2Assets.Slideshow         => SegoeUISymbol.Slideshow,
        SegoeMDL2Assets.Calendar          => SegoeUISymbol.Calendar,
        SegoeMDL2Assets.Trim              => SegoeUISymbol.Trim,
        SegoeMDL2Assets.NewWindow         => SegoeUISymbol.NewWindow,
        SegoeMDL2Assets.SaveLocal         => SegoeUISymbol.SaveLocal,
        SegoeMDL2Assets.Redo              => SegoeUISymbol.Redo,
        SegoeMDL2Assets.Undo              => SegoeUISymbol.Undo,
        SegoeMDL2Assets.Crop              => SegoeUISymbol.Crop,
        SegoeMDL2Assets.OpenWith          => SegoeUISymbol.OpenWith,
        SegoeMDL2Assets.Rotate            => SegoeUISymbol.Rotate,
        SegoeMDL2Assets.SetLockScreen     => SegoeUISymbol.SetLockScreen,
        SegoeMDL2Assets.Flag              => SegoeUISymbol.Flag,
        SegoeMDL2Assets.Page              => SegoeUISymbol.Page,
        SegoeMDL2Assets.BrowsePhotos      => SegoeUISymbol.BrowsePhotos,
        SegoeMDL2Assets.TouchPointer      => SegoeUISymbol.TouchPointer,
        SegoeMDL2Assets.Highlight         => SegoeUISymbol.Highlight,
        SegoeMDL2Assets.OtherUser         => SegoeUISymbol.OtherUser,
        SegoeMDL2Assets.Admin             => SegoeUISymbol.Admin,
        SegoeMDL2Assets.CC                => SegoeUISymbol.CC,
        SegoeMDL2Assets.Home              => SegoeUISymbol.Home,
        SegoeMDL2Assets.View              => SegoeUISymbol.View,
        SegoeMDL2Assets.Previous          => SegoeUISymbol.Previous,
        SegoeMDL2Assets.Next              => SegoeUISymbol.Next,
        SegoeMDL2Assets.Sync              => SegoeUISymbol.Sync,
        SegoeMDL2Assets.Download          => SegoeUISymbol.Download,
        SegoeMDL2Assets.Help              => SegoeUISymbol.Help,
        SegoeMDL2Assets.Upload            => SegoeUISymbol.Upload,
        SegoeMDL2Assets.Emoji             => SegoeUISymbol.Emoji,
        SegoeMDL2Assets.TwoPage           => SegoeUISymbol.TwoPage,
        SegoeMDL2Assets.LeaveChat         => SegoeUISymbol.LeaveChat,
        SegoeMDL2Assets.MailForward       => SegoeUISymbol.MailForward,
        SegoeMDL2Assets.RotateCamera      => SegoeUISymbol.RotateCamera,
        SegoeMDL2Assets.ClosePane         => SegoeUISymbol.ClosePane,
        SegoeMDL2Assets.OpenPane          => SegoeUISymbol.OpenPane,
        SegoeMDL2Assets.PreviewLink       => SegoeUISymbol.PreviewLink,
        SegoeMDL2Assets.AttachCamera      => SegoeUISymbol.AttachCamera,
        SegoeMDL2Assets.ZoomIn            => SegoeUISymbol.ZoomIn,
        SegoeMDL2Assets.Bookmarks         => SegoeUISymbol.Bookmarks,
        SegoeMDL2Assets.Document          => SegoeUISymbol.Document,
        SegoeMDL2Assets.ProtectedDocument => SegoeUISymbol.ProtectedDocument,
        SegoeMDL2Assets.ViewAll           => SegoeUISymbol.ViewAll,
        SegoeMDL2Assets.VideoChat         => SegoeUISymbol.VideoChat,
        SegoeMDL2Assets.Switch            => SegoeUISymbol.Switch,
        SegoeMDL2Assets.Rename            => SegoeUISymbol.Rename,
        SegoeMDL2Assets.Go                => SegoeUISymbol.Go,
        SegoeMDL2Assets.Remote            => SegoeUISymbol.Remote,
        SegoeMDL2Assets.Shuffle           => SegoeUISymbol.Shuffle,
        SegoeMDL2Assets.SelectAll         => SegoeUISymbol.SelectAll,
        SegoeMDL2Assets.Orientation       => SegoeUISymbol.Orientation,
        SegoeMDL2Assets.Import            => SegoeUISymbol.Import,
        SegoeMDL2Assets.ImportAll         => SegoeUISymbol.ImportAll,
        SegoeMDL2Assets.Folder            => SegoeUISymbol.Folder,
        SegoeMDL2Assets.Webcam            => SegoeUISymbol.Webcam,
        SegoeMDL2Assets.Caption           => SegoeUISymbol.Caption,
        SegoeMDL2Assets.ShowResults       => SegoeUISymbol.ShowResults,
        SegoeMDL2Assets.Message           => SegoeUISymbol.Message,
        SegoeMDL2Assets.CalendarDay       => SegoeUISymbol.CalendarDay,
        SegoeMDL2Assets.CalendarWeek      => SegoeUISymbol.CalendarWeek,
        SegoeMDL2Assets.Characters        => SegoeUISymbol.Characters,
        SegoeMDL2Assets.MailReplyAll      => SegoeUISymbol.MailReplyAll,
        SegoeMDL2Assets.Read              => SegoeUISymbol.Read,
        SegoeMDL2Assets.ShowBcc           => SegoeUISymbol.ShowBcc,
        SegoeMDL2Assets.HideBcc           => SegoeUISymbol.HideBcc,
        SegoeMDL2Assets.Cut               => SegoeUISymbol.Cut,
        SegoeMDL2Assets.Copy              => SegoeUISymbol.Copy,
        SegoeMDL2Assets.Important         => SegoeUISymbol.Important,
        SegoeMDL2Assets.MailReply         => SegoeUISymbol.MailReply,
        SegoeMDL2Assets.Sort              => SegoeUISymbol.Sort,
        SegoeMDL2Assets.DisconnectDrive   => SegoeUISymbol.DisconnectDrive,
        SegoeMDL2Assets.MapDrive          => SegoeUISymbol.MapDrive,
        SegoeMDL2Assets.ContactPresence   => SegoeUISymbol.ContactPresence,
        SegoeMDL2Assets.Priority          => SegoeUISymbol.Priority,
        SegoeMDL2Assets.GoToToday         => SegoeUISymbol.GoToToday,
        SegoeMDL2Assets.Font              => SegoeUISymbol.Font,
        SegoeMDL2Assets.FontColor         => SegoeUISymbol.FontColor,
        SegoeMDL2Assets.Contact2          => SegoeUISymbol.Contact2,
        SegoeMDL2Assets.Audio             => SegoeUISymbol.Audio,
        SegoeMDL2Assets.Permissions       => SegoeUISymbol.Permissions,
        SegoeMDL2Assets.DisableUpdates    => SegoeUISymbol.DisableUpdates,
        SegoeMDL2Assets.Unfavorite        => SegoeUISymbol.Unfavorite,
        SegoeMDL2Assets.OpenLocal         => SegoeUISymbol.OpenLocal,
        SegoeMDL2Assets.Italic            => SegoeUISymbol.Italic,
        SegoeMDL2Assets.Underline         => SegoeUISymbol.Underline,
        SegoeMDL2Assets.Bold              => SegoeUISymbol.Bold,
        SegoeMDL2Assets.MoveToFolder      => SegoeUISymbol.MoveToFolder,
        SegoeMDL2Assets.LikeDislike       => SegoeUISymbol.LikeDislike,
        SegoeMDL2Assets.Dislike           => SegoeUISymbol.Dislike,
        SegoeMDL2Assets.Like              => SegoeUISymbol.Like,
        SegoeMDL2Assets.AlignRight        => SegoeUISymbol.AlignRight,
        SegoeMDL2Assets.AlignCenter       => SegoeUISymbol.AlignCenter,
        SegoeMDL2Assets.AlignLeft         => SegoeUISymbol.AlignLeft,
        SegoeMDL2Assets.OpenFile          => SegoeUISymbol.OpenFile,
        SegoeMDL2Assets.ClearSelection    => SegoeUISymbol.ClearSelection,
        SegoeMDL2Assets.FontDecrease      => SegoeUISymbol.FontDecrease,
        SegoeMDL2Assets.FontIncrease      => SegoeUISymbol.FontIncrease,
        SegoeMDL2Assets.FontSize          => SegoeUISymbol.FontSize,
        SegoeMDL2Assets.CellPhone         => SegoeUISymbol.CellPhone,
        SegoeMDL2Assets.Reshare           => SegoeUISymbol.Reshare,
        SegoeMDL2Assets.Tag               => SegoeUISymbol.Tag,
        SegoeMDL2Assets.RepeatOne         => SegoeUISymbol.RepeatOne,
        SegoeMDL2Assets.RepeatAll         => SegoeUISymbol.RepeatAll,
        SegoeMDL2Assets.Calculator        => SegoeUISymbol.Calculator,
        SegoeMDL2Assets.Directions        => SegoeUISymbol.Directions,
        SegoeMDL2Assets.Library           => SegoeUISymbol.Library,
        SegoeMDL2Assets.PostUpdate        => SegoeUISymbol.PostUpdate,
        SegoeMDL2Assets.NewFolder         => SegoeUISymbol.NewFolder,
        SegoeMDL2Assets.CalendarReply     => SegoeUISymbol.CalendarReply,
        SegoeMDL2Assets.UnsyncFolder      => SegoeUISymbol.UnsyncFolder,
        SegoeMDL2Assets.SyncFolder        => SegoeUISymbol.SyncFolder,
        SegoeMDL2Assets.BlockContact      => SegoeUISymbol.BlockContact,
        SegoeMDL2Assets.SwitchApps        => SegoeUISymbol.SwitchApps,
        SegoeMDL2Assets.AddFriend         => SegoeUISymbol.AddFriend,
        SegoeMDL2Assets.GoToStart         => SegoeUISymbol.GoToStart,
        SegoeMDL2Assets.ZeroBars          => SegoeUISymbol.ZeroBars,
        SegoeMDL2Assets.OneBar            => SegoeUISymbol.OneBar,
        SegoeMDL2Assets.TwoBars           => SegoeUISymbol.TwoBars,
        SegoeMDL2Assets.ThreeBars         => SegoeUISymbol.ThreeBars,
        SegoeMDL2Assets.FourBars          => SegoeUISymbol.FourBars,
        SegoeMDL2Assets.World             => SegoeUISymbol.World,
        SegoeMDL2Assets.Comment           => SegoeUISymbol.Comment,
        SegoeMDL2Assets.MusicInfo         => SegoeUISymbol.MusicInfo,
        SegoeMDL2Assets.DockLeft          => SegoeUISymbol.DockLeft,
        SegoeMDL2Assets.DockRight         => SegoeUISymbol.DockRight,
        SegoeMDL2Assets.DockBottom        => SegoeUISymbol.DockBottom,
        SegoeMDL2Assets.Repair            => SegoeUISymbol.Repair,
        SegoeMDL2Assets.Accounts          => SegoeUISymbol.Accounts,
        SegoeMDL2Assets.Manage            => SegoeUISymbol.Manage,
        SegoeMDL2Assets.Street            => SegoeUISymbol.Street,
        SegoeMDL2Assets.Photo             => SegoeUISymbol.Photo,
        SegoeMDL2Assets.List              => SegoeUISymbol.List,
        _                                 => SegoeUISymbol.None
    };
}