// <auto-generated />
namespace Stylish.Unicode;

/// <summary>
/// Emoji groups (Unicode 15.1)
/// </summary>
/// <remarks>
/// Source: https://unicode.org/Public/emoji/15.1/emoji-test.txt
/// </remarks>

public enum EmojiGroup
{
    None,

    /// <summary>Activities (85 emojis)</summary>
    Activities,

    /// <summary>Animals &amp; Nature (153 emojis)</summary>
    AnimalsAndNature,

    /// <summary>Component (9 emojis)</summary>
    Component,

    /// <summary>Flags (269 emojis)</summary>
    Flags,

    /// <summary>Food &amp; Drink (135 emojis)</summary>
    FoodAndDrink,

    /// <summary>Objects (262 emojis)</summary>
    Objects,

    /// <summary>People &amp; Body (2260 emojis)</summary>
    PeopleAndBody,

    /// <summary>Smileys &amp; Emotion (168 emojis)</summary>
    SmileysAndEmotion,

    /// <summary>Symbols (223 emojis)</summary>
    Symbols,

    /// <summary>Travel &amp; Places (218 emojis)</summary>
    TravelAndPlaces
}