// <auto-generated />
namespace Stylish.Unicode;

/// <summary>
/// Emoji subgroups (Unicode 15.1)
/// </summary>
/// <remarks>
/// Source: https://unicode.org/Public/emoji/15.1/emoji-test.txt
/// </remarks>

public enum EmojiSubgroup
{
    None,

    /// <summary>Alphanumeric (39 emojis)</summary>
    Alphanumeric,

    /// <summary>Animal <i>(amphibian)</i> (1 emojis)</summary>
    AnimalAmphibian,

    /// <summary>Animal <i>(bird)</i> (22 emojis)</summary>
    AnimalBird,

    /// <summary>Animal <i>(bug)</i> (16 emojis)</summary>
    AnimalBug,

    /// <summary>Animal <i>(mammal)</i> (66 emojis)</summary>
    AnimalMammal,

    /// <summary>Animal <i>(marine)</i> (12 emojis)</summary>
    AnimalMarine,

    /// <summary>Animal <i>(reptile)</i> (8 emojis)</summary>
    AnimalReptile,

    /// <summary>Arrow (21 emojis)</summary>
    Arrow,

    /// <summary>Arts &amp; Crafts (7 emojis)</summary>
    ArtsAndCrafts,

    /// <summary>Av <i>(symbol)</i> (25 emojis)</summary>
    AvSymbol,

    /// <summary>Award <i>(medal)</i> (6 emojis)</summary>
    AwardMedal,

    /// <summary>Body <i>(parts)</i> (48 emojis)</summary>
    BodyParts,

    /// <summary>Book <i>(paper)</i> (17 emojis)</summary>
    BookPaper,

    /// <summary>Cat <i>(face)</i> (9 emojis)</summary>
    CatFace,

    /// <summary>Clothing (47 emojis)</summary>
    Clothing,

    /// <summary>Computer (14 emojis)</summary>
    Computer,

    /// <summary>Country <i>(flag)</i> (258 emojis)</summary>
    CountryFlag,

    /// <summary>Currency (2 emojis)</summary>
    Currency,

    /// <summary>Dishware (7 emojis)</summary>
    Dishware,

    /// <summary>Drink (20 emojis)</summary>
    Drink,

    /// <summary>Emotion (14 emojis)</summary>
    Emotion,

    /// <summary>Event (21 emojis)</summary>
    Event,

    /// <summary>Face <i>(affection)</i> (9 emojis)</summary>
    FaceAffection,

    /// <summary>Face <i>(concerned)</i> (26 emojis)</summary>
    FaceConcerned,

    /// <summary>Face <i>(costume)</i> (8 emojis)</summary>
    FaceCostume,

    /// <summary>Face <i>(glasses)</i> (3 emojis)</summary>
    FaceGlasses,

    /// <summary>Face <i>(hand)</i> (7 emojis)</summary>
    FaceHand,

    /// <summary>Face <i>(hat)</i> (3 emojis)</summary>
    FaceHat,

    /// <summary>Face <i>(negative)</i> (8 emojis)</summary>
    FaceNegative,

    /// <summary>Face <i>(neutral skeptical)</i> (16 emojis)</summary>
    FaceNeutralSkeptical,

    /// <summary>Face <i>(sleepy)</i> (5 emojis)</summary>
    FaceSleepy,

    /// <summary>Face <i>(smiling)</i> (14 emojis)</summary>
    FaceSmiling,

    /// <summary>Face <i>(tongue)</i> (6 emojis)</summary>
    FaceTongue,

    /// <summary>Face <i>(unwell)</i> (12 emojis)</summary>
    FaceUnwell,

    /// <summary>Family (337 emojis)</summary>
    Family,

    /// <summary>Flag (8 emojis)</summary>
    Flag,

    /// <summary>Food <i>(asian)</i> (17 emojis)</summary>
    FoodAsian,

    /// <summary>Food <i>(fruit)</i> (20 emojis)</summary>
    FoodFruit,

    /// <summary>Food <i>(marine)</i> (5 emojis)</summary>
    FoodMarine,

    /// <summary>Food <i>(prepared)</i> (34 emojis)</summary>
    FoodPrepared,

    /// <summary>Food <i>(sweet)</i> (14 emojis)</summary>
    FoodSweet,

    /// <summary>Food <i>(vegetable)</i> (18 emojis)</summary>
    FoodVegetable,

    /// <summary>Game (24 emojis)</summary>
    Game,

    /// <summary>Gender (3 emojis)</summary>
    Gender,

    /// <summary>Geometric (34 emojis)</summary>
    Geometric,

    /// <summary>Hair <i>(style)</i> (4 emojis)</summary>
    HairStyle,

    /// <summary>Hand <i>(fingers closed)</i> (36 emojis)</summary>
    HandFingersClosed,

    /// <summary>Hand <i>(fingers open)</i> (66 emojis)</summary>
    HandFingersOpen,

    /// <summary>Hand <i>(fingers partial)</i> (54 emojis)</summary>
    HandFingersPartial,

    /// <summary>Hand <i>(prop)</i> (18 emojis)</summary>
    HandProp,

    /// <summary>Hand <i>(single finger)</i> (42 emojis)</summary>
    HandSingleFinger,

    /// <summary>Hands (62 emojis)</summary>
    Hands,

    /// <summary>Heart (25 emojis)</summary>
    Heart,

    /// <summary>Hotel (2 emojis)</summary>
    Hotel,

    /// <summary>Household (25 emojis)</summary>
    Household,

    /// <summary>Keycap (13 emojis)</summary>
    Keycap,

    /// <summary>Light &amp; Video (16 emojis)</summary>
    LightAndVideo,

    /// <summary>Lock (6 emojis)</summary>
    Lock,

    /// <summary>Mail (13 emojis)</summary>
    Mail,

    /// <summary>Math (6 emojis)</summary>
    Math,

    /// <summary>Medical (7 emojis)</summary>
    Medical,

    /// <summary>Money (10 emojis)</summary>
    Money,

    /// <summary>Monkey <i>(face)</i> (3 emojis)</summary>
    MonkeyFace,

    /// <summary>Music (9 emojis)</summary>
    Music,

    /// <summary>Musical <i>(instrument)</i> (11 emojis)</summary>
    MusicalInstrument,

    /// <summary>Office (23 emojis)</summary>
    Office,

    /// <summary>Other <i>(object)</i> (9 emojis)</summary>
    OtherObject,

    /// <summary>Other <i>(symbol)</i> (21 emojis)</summary>
    OtherSymbol,

    /// <summary>Person (168 emojis)</summary>
    Person,

    /// <summary>Person <i>(activity)</i> (327 emojis)</summary>
    PersonActivity,

    /// <summary>Person <i>(fantasy)</i> (157 emojis)</summary>
    PersonFantasy,

    /// <summary>Person <i>(gesture)</i> (180 emojis)</summary>
    PersonGesture,

    /// <summary>Person <i>(resting)</i> (30 emojis)</summary>
    PersonResting,

    /// <summary>Person <i>(role)</i> (492 emojis)</summary>
    PersonRole,

    /// <summary>Person <i>(sport)</i> (233 emojis)</summary>
    PersonSport,

    /// <summary>Person <i>(symbol)</i> (10 emojis)</summary>
    PersonSymbol,

    /// <summary>Phone (6 emojis)</summary>
    Phone,

    /// <summary>Place <i>(building)</i> (27 emojis)</summary>
    PlaceBuilding,

    /// <summary>Place <i>(geographic)</i> (9 emojis)</summary>
    PlaceGeographic,

    /// <summary>Place <i>(map)</i> (7 emojis)</summary>
    PlaceMap,

    /// <summary>Place <i>(other)</i> (17 emojis)</summary>
    PlaceOther,

    /// <summary>Place <i>(religious)</i> (6 emojis)</summary>
    PlaceReligious,

    /// <summary>Plant <i>(flower)</i> (12 emojis)</summary>
    PlantFlower,

    /// <summary>Plant <i>(other)</i> (16 emojis)</summary>
    PlantOther,

    /// <summary>Punctuation (7 emojis)</summary>
    Punctuation,

    /// <summary>Religion (13 emojis)</summary>
    Religion,

    /// <summary>Science (7 emojis)</summary>
    Science,

    /// <summary>Skin Tone (5 emojis)</summary>
    SkinTone,

    /// <summary>Sky &amp; Weather (47 emojis)</summary>
    SkyAndWeather,

    /// <summary>Sound (9 emojis)</summary>
    Sound,

    /// <summary>Sport (27 emojis)</summary>
    Sport,

    /// <summary>Subdivision <i>(flag)</i> (3 emojis)</summary>
    SubdivisionFlag,

    /// <summary>Time (31 emojis)</summary>
    Time,

    /// <summary>Tool (26 emojis)</summary>
    Tool,

    /// <summary>Transport <i>(air)</i> (13 emojis)</summary>
    TransportAir,

    /// <summary>Transport <i>(ground)</i> (50 emojis)</summary>
    TransportGround,

    /// <summary>Transport <i>(sign)</i> (13 emojis)</summary>
    TransportSign,

    /// <summary>Transport <i>(water)</i> (9 emojis)</summary>
    TransportWater,

    /// <summary>Warning (13 emojis)</summary>
    Warning,

    /// <summary>Writing (7 emojis)</summary>
    Writing,

    /// <summary>Zodiac (13 emojis)</summary>
    Zodiac
}